### ISSUE TITLE
out-office-app not working

### ISSUE THREAD

**Issue by himpierre** [graywolf336/RocketChatApps#4]
Hello @graywolf336 

Just tried the very welcome out-of-office app but it does not seem to do anything. I issued "/out-of-office out" and expected my chat partner to get an out of office message when trying to contact me via dm but he is not. Any hints?

Rocketchat 0.70.3 by the way.

thanks and cheers

**Comment by graywolf336** [comment]
Okay, so on the web browser. I'll test again, as it should be working 🤔

**Comment by graywolf336** [comment]
![image](https://user-images.githubusercontent.com/850391/47040988-454a8a00-d14d-11e8-8c23-ed5270977c27.png)

Yeah, something happened with the latest release of Rocket.Chat. :(

**Comment by himpierre** [comment]
Is this app supposed to work with 0.71.1 again?

**Comment by Plantox** [comment]
28 days later and apparently still not working :/
Is there going to be any fix soon?

**Comment by graywolf336** [comment]
Waiting on this: https://github.com/RocketChat/Rocket.Chat.Apps-engine/pull/87

**Comment by himpierre** [comment]
Works with 0.72.0-rc0.
